name: Mirror and run GitLab CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: ailisp/gitlab-mirror-and-ci-action@master
      with:
        args: "ailisp/aaa"
      env:
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: "ailisp"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "14523462"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
